name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build-maven:
    name: Build Maven

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        jdk: [17, 21]
        experimental: [false]
        include:
          - jdk: 25
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "semeru"
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --file pom.xml -Djava.version=${{ matrix.jdk }} package
      - run: mkdir staging && cp cics-java-liberty-springboot-jdbc-app/target/*.war staging
      - uses: actions/upload-artifact@v4
        with:
          name: cics-java-liberty-sprintboot-jdbc (Maven, Java ${{ matrix.jdk }})
          path: staging

  build-mvnw:
    name: Build Maven Wrapper

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        jdk: [17, 21]
        experimental: [false]
        include:
          - jdk: 25
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "semeru"
          cache: maven
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots --file pom.xml -Djava.version=${{ matrix.jdk }} package

  build-gradle:
    name: Build Gradle
    
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        jdk: [17, 21]
        experimental: [false]
        include:
          - jdk: 25
            experimental: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'semeru'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew bootWar -Pjava_version=${{ matrix.jdk }}
      
  build-gradlew:
    name: Build Gradle wrapper
    
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        jdk: [17, 21]
        experimental: [false]
        include:
          - jdk: 25
            experimental: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'semeru'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew build bootWar -Pjava_version=${{ matrix.jdk }}
